                    - alias: "Wesley Away"
                      condition:
                        condition: state
                        entity_id: input_boolean.wesley_home
                        state: 'on'
                    # Will only trigger if all are 'not_home'
                      trigger:
                          platform: template
                          value_template: "{% if (is_state('device_tracker.wesnote9','not_home')) and (is_state('device_tracker.wesnote9','not_home')) %}true{% endif %}"
                      action:
                          service: homeassistant.turn_off
                          entity_id: input_boolean.wesley_home
                    
                    - alias: "Wesley Home"
                      condition:
                        condition: state
                        entity_id: input_boolean.wesley_home
                        state: 'off'
                    # Will trigger if any of the below are 'home'
                      trigger:
                        - platform: state
                          entity_id: device_tracker.wesnote9
                          to: 'home'
                        - platform: state
                          entity_id: device_tracker.wesnote9
                          to: 'home'
                      action:
                          service: homeassistant.turn_on
                          entity_id: input_boolean.wesley_home
                    
                    - alias: "Andrea Away"
                      condition:
                        condition: state
                        entity_id: input_boolean.andrea_home
                        state: 'on'
                    # Will only trigger if all are 'not_home'
                      trigger:
                          platform: template
                          value_template: "{% if (is_state('device_tracker.galaxy8','not_home')) and (is_state('device_tracker.galaxy8_asus','not_home')) %}true{% endif %}"
                      action:
                          service: homeassistant.turn_off
                          entity_id: input_boolean.andrea_home
                    
                    - alias: "Andrea Home"
                      condition:
                        condition: state
                        entity_id: input_boolean.andrea_home
                        state: 'off'
                    # Will trigger if any of the below are 'home'
                      trigger:
                        - platform: state
                          entity_id: device_tracker.galaxy8
                          to: 'home'
                        - platform: state
                          entity_id: device_tracker.galaxy8_asus
                          to: 'home'
                      action:
                          service: homeassistant.turn_on
                          entity_id: input_boolean.andrea_home]
